import React from "react";
import { useAuth } from "@contexts/AuthContext";
import { useRouter } from "next/router";
import FullPageLoadingSpinner from "@components/shared/FullPageLoadingSpinner";
import { useToast } from "@chakra-ui/react";

const OnlyLoggedIn = ({ children }) => {
	const toast = useToast();
	const router = useRouter();
	const { currentUser } = useAuth();

	if (!currentUser) {
		//! The last page (from which the push is being called) re-renders while router.push is being used.
		//! Unwanted Error and Warning are generated by these toast on re-render.
		// if (!toast.isActive("not-logged-in")) {
		// 	toast({
		// 		id: "not-logged-in",
		// 		title: "Not Logged in.",
		// 		description: "You must be logged in to view this page.",
		// 		status: "error",
		// 		duration: 9000,
		// 		isClosable: true,
		// 	});
		// }
		router.push("/auth/login");
		return <FullPageLoadingSpinner />;
	}

	return <>{children}</>;
};

export default OnlyLoggedIn;
